{{ if .Values.activeFat }}
{{ $dot := . }}
        {{ $Values := .Values }}
        {{ $Release := .Release }}
        {{ $Chart := .Chart }}
        {{ $Template := .Template }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "perfumeriasloli.fullname" $dot }}
  namespace: default
  labels:
          {{- include "perfumeriasloli.labels" $dot | nindent 6 }}
spec:
  replicas: {{ $Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "perfumeriasloli.name" $dot }}
      app.kubernetes.io/instance: {{ $Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "perfumeriasloli.name" $dot }}
        app.kubernetes.io/instance: {{ $Release.Name }}
    spec:
      containers:
        - name: {{ include "perfumeriasloli.fullname" $dot }}
          image: "perfumeriasloli:local"
          imagePullPolicy: IfNotPresent
          env:
            - name: "JAVA_TOOL_OPTIONS"
              value: {{ $Values.env }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: {{ $Values.initialDelaySeconds }} #will wait this sec after start of the container to check the liveness. Default 0
            periodSeconds: 10 #will check this every this seconds. Default 10
            timeoutSeconds: 10 #the request has maximum this seconds to return a response
            failureThreshold: 3 #if after this tries will restart the container. Default 3
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: {{ $Values.initialDelaySeconds }} #will wait this sec after start of the container to check the liveness. Default 0
            periodSeconds: 3 #will check this every this seconds. Default 10
            timeoutSeconds: 3 #the request has maxmium this seconds to return a response
            failureThreshold: 3 #if after this tries the node is marked as Unready. Default 3
          resources:
              {{- toYaml $Values.resources | nindent 20 }}
{{ end }}
