{{ if .Values.activeFat }}
{{ $dot := . }}
        {{ $Values := .Values }}
        {{ $Release := .Release }}
apiVersion: v1
kind: Service
metadata:
    name: {{ include "perfumeriasloli.fullname" $dot }}
    namespace: default
    labels:
        {{- include "perfumeriasloli.labels" $dot | nindent 8 }}
spec:
    type: {{ $Values.service.type }}
    ports:
        - port: {{ $Values.service.port }}
          targetPort: http
          protocol: TCP
          name: http
    selector:
        app.kubernetes.io/name: {{ include "perfumeriasloli.name" $dot }}
        app.kubernetes.io/instance: {{ $Release.Name }}
        {{ end }}
