{{ if .Values.activeSeparated }}
{{ $dot := . }}
        {{ $Values := .Values }}
        {{ $Release := .Release }}
        {{ range $bookingOperation_index, $bookingOperation_element := $Values.featureOperations}}
apiVersion: v1
kind: Service
metadata:
    name: {{ include "perfumeriasloli.fullname" $dot }}--{{$bookingOperation_element.name}}
    namespace: default
    labels:
            {{- include "perfumeriasloli.labels" $dot | nindent 8 }}
        bookingOperation: {{$bookingOperation_element.name}}
spec:
    type: {{ $Values.service.type }}
    ports:
        - port: {{ $Values.service.port }}
          targetPort: http
          protocol: TCP
          name: http
    selector:
        app.kubernetes.io/name: {{ include "perfumeriasloli.name" $dot }}
        app.kubernetes.io/instance: {{ $Release.Name }}
        bookingOperation: {{$bookingOperation_element.name}}
---
        {{end}}
{{ end }}
