# Run simulate: helm install --dry-run --debug -f perfumeriasloli/values.yaml perfumeriasloli
# Deploy on Kubernetes: helm install -f perfumeriasloli/values.yaml perfumeriasloli

# Run simulate: helm install --dry-run --debug -f perfumeriasloli/values.yaml -f perfumeriasloli/values-separated.yaml perfumeriasloli
# Deploy on Kubernetes: helm install -f perfumeriasloli/values.yaml -f perfumeriasloli/values-separated.yaml perfumeriasloli

# Run simulate: helm install --dry-run --debug -f perfumeriasloli/values.yaml -f perfumeriasloli/values-aws-apac.yaml perfumeriasloli
# Deploy on Kubernetes: helm install -f perfumeriasloli/values.yaml -f perfumeriasloli/values-aws-apac.yaml perfumeriasloli

# Run simulate: helm install --dry-run --debug -f perfumeriasloli/values.yaml -f perfumeriasloli/values-gke-europe.yaml perfumeriasloli
# Deploy on Kubernetes: helm install -f perfumeriasloli/values.yaml -f perfumeriasloli/values-gke-europe.yaml perfumeriasloli

replicaCount: 1
initialDelaySeconds: 100
activeFat: true
activeSeparated: false
env: "-XX:+UseG1GC -XX:+PrintGC -Xss256k -Xms1500M -Xmx1500M -Dfile.encoding=UTF-8 -Djava.security.egd=file:/dev/urandom -Dspring.application.name=perfumerias-loli -Dspring.profiles.active=fat"

imagePullSecrets: []
nameOverride: "perfumerias-loli"
fullnameOverride: ""
featureOperations:
  - name: dummy
    path: /dummy
    env: "dummy"
    replicaCount: 0
    initialDelaySeconds: 0
    resources:
      limits:
        cpu: '500m'
        memory: 200Mi
      requests:
        cpu: '500m'
        memory: 200Mi
service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}

resources:
  limits:
    cpu: '500m'
    memory: 2000Mi
  requests:
    cpu: '500m'
    memory: 2000Mi
